### ISSUE TITLE
CSV format in tobii file is incorrect.

### ISSUE THREAD

**Issue by redeian** [SMU-Ubicomp-Lab/PupilwareM#1]
![image](https://cloud.githubusercontent.com/assets/1762546/18964323/f98d2b74-863d-11e6-9c21-ca257971551f.png)

If you can make,  [time, tobiiTime, left, right] would be easier to load to DataFrame.

**Comment by dxywill** [comment]
Put them to separate files 88c04adb5c1ed43b62b6a200fb720559c68a8a27
