### ISSUE TITLE
[crash] tobiiSubjectIds is failed if it failed to connect to Tobii Server

### ISSUE THREAD

**Issue by redeian** [SMU-Ubicomp-Lab/PupilwareM#2]
This line is crash, if it failed to connect to Tobii server.
![image](https://cloud.githubusercontent.com/assets/1762546/18964461/9ab52b82-863e-11e6-90a7-ebcaf532fc34.png)

I also happens through out the system with the similar style of referencing Tobii code.

**Comment by dxywill** [comment]
This issue should be fixed by this commit 533a081ce30a75c3cbd7485d30a4b4b99095b8ae

**Comment by redeian** [comment]
No longer crash.
