### ISSUE TITLE
surveys file is not in CSV format

### ISSUE THREAD

**Issue by redeian** [SMU-Ubicomp-Lab/PupilwareM#4]
It is easier and more reliable to read csv files during analysis.

![image](https://cloud.githubusercontent.com/assets/1762546/18964900/846e9348-8640-11e6-94b5-c48dcc5bfdc7.png)

**Comment by dxywill** [comment]
Should be fixed by this commit 51bf120f3570681f74e189f03f692a8c27598c5f

**Comment by redeian** [comment]
FIXED! Thank you
