### ISSUE TITLE
Do tobii has eye distance data

### ISSUE THREAD

**Issue by redeian** [SMU-Ubicomp-Lab/PupilwareM#7]
I wonder if Tobii give eye distance, face location, gaze location, and so on.
The more data, the better.

Now our Pupil system store pupil size as a ratio of rawPupilSize/eyeDistance.

**Comment by dxywill** [comment]
Tobii Glass does not give eye distance directly, but it could be calculated from the coordinate system

**Comment by dxywill** [comment]
Save pupil centers to calculate distance 5b08b1b0788995a15cb911e492f7e223377dd1ac

**Comment by redeian** [comment]
Sweet~ THANKS!
