### ISSUE TITLE
ACT Survey CSV is incorrect

### ISSUE THREAD

**Issue by redeian** [SMU-Ubicomp-Lab/PupilwareM#8]
![image](https://cloud.githubusercontent.com/assets/1762546/19005870/72b1b4cc-8722-11e6-907c-7ec808e9fb87.png)

**Comment by dxywill** [comment]
This is fixed by commit 3c6be4342edcfc892af42756cd648542d4105ac5

**Comment by redeian** [comment]
Fixed!
